### ISSUE TITLE
Allow nacks

### ISSUE THREAD

**Issue by AntonLydike** [maansthoernvik/rabbitmq_client#27]
There is currently no way to handle sending a nack()

Maybe the consumer should send a nack() when he recieves an error from the callback? I think that that would be a pretty good start.

Maybe I can get a quick PR in later this week?

**Comment by maansthoernvik** [comment]
I opted to leave the message handling purely in that hands of the callback implementer. My reasoning is that I do not want to interfere in what action they may want to take for a particular message. There are more parameters to add related to message handling, but I will add these on request. Feel free to open more issues if you need some additional control.
